### ISSUE TITLE
Pause Image is not Exactly Center within Border Circle

### ISSUE THREAD

**Issue by Stunner** [raphaelschaad/RSPlayPauseButton#3]
It's ever so slightly skewed to the left: <img width="47" alt="screen shot 2016-05-06 at 11 38 13 pm" src="https://cloud.githubusercontent.com/assets/1133897/15090670/23d69540-13e4-11e6-8277-e41ea50637ed.png">

**Comment by raphaelschaad** [comment]
3ec2071 fixes this.

**Comment by Stunner** [comment]
🚀
